title: Markdown[Маркдаун]
author: Даниел Димитров
email:
description: Въведение в маркдаун на български език
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Markdown-mark.svg/200px-Markdown-mark.svg.png
baseurl: /markdown
url: htps://danny-dimitrov.github.io/
google_analytics: UA-145771380-1

theme: jekyll-theme-minimal
plugins:
  - jemoji
